### ISSUE TITLE
RequireJS support

### ISSUE THREAD

**Issue by giero** [GeniusesOfSymfony/WebSocketBundle#115]
Hi,

Is it possible to use js client with [RequireJS](http://requirejs.org/)? For now I have in my config.yml

```
assetic:
  assets:
    gos_web_socket:
      inputs:
        - "@GosWebSocketBundle/Resources/public/js/vendor/autobahn.min.js"
        - "@GosWebSocketBundle/Resources/public/js/gos_web_socket_client.js"
```

and then

``` javascript
requirejs.config({
    baseUrl: 'js',
    paths: {
        gos_web_socket: '../assetic/gos_web_socket'
    }
});
```

But 2 problems:
1) every time I've got error `ReferenceError: ab is not defined` (it's from autobahn.min.js)
2) will I be able to use WS in requirejs modules? For example by shim config like:

``` javascript
requirejs.config({
    baseUrl: 'js',
    paths: {
        gos_web_socket: '../assetic/gos_web_socket'
    },
    shim: {
        gos_web_socket: {
            exports: 'WS'
        }
    }
});
```

and then

``` javascript
define(['gos_web_socket'], function (WS) {
    var webSocket = WS.connect('ws://127.0.0.1:8080');
    //... etc
});
```

Best Regards
