### ISSUE TITLE
Problem service pubsubrouter.websocket

### ISSUE THREAD

**Issue by cristhianfernandez01** [GeniusesOfSymfony/WebSocketBundle#13]
I have a problem when trying to start the websocket server. I get the following error:
The service "gos_web_socket.router.wamp" has a dependency on a non-existent service "gos_pubsub_router.websocket".

I have installed the bundle PubSubRouter. What can give solution to this problem ?. I would appreciate your help very much.

My configuration for the bundle is:

    gos_web_socket:
        server:
            port: 8080
            host: 127.0.0.1

**Comment by ProPheT777** [comment]
Thank you for reporting it. I think I must start to tag pubsub router to avoid this.

First you don't need to install pubsub router by yourself because he is already loaded by websocket bundle & configured (you just have to add your routing file).

I will fix it as soon as possible

**Comment by cristhianfernandez01** [comment]
Thank you very much for your quick response. I will be aware

**Comment by ProPheT777** [comment]
I have released v1.0.2, run composer update, it should solved it ! :)

BTW, if you continue the installation until the routing configuration it work.

**Comment by cristhianfernandez01** [comment]
It worked perfectly. Thank you very much again for your help. The bundle is excellent

**Comment by ProPheT777** [comment]
> The bundle is excellent

Thank you very much !

**Comment by cristhianfernandez01** [comment]
How do I make so you can use the routes with the bundle PubSubRouter? Because if I set routes through the option "router" I'm aking the same problem, ie I get the same error. Otherwise, how could do to dispense with this bundle (PubSubRouter)?

**Comment by ProPheT777** [comment]
Sorry but i don't understand :(

WebsocketBundle forward all configs under "router" key to "PubSubRouter" in order to keep the installation very easy. 

Here an example : https://github.com/ProPheT777/real_time_bidirectional_notification-symfony2-redis-websocket-pubsub/commits?author=ProPheT777

-> May be the doc is wrong ?

**Comment by cristhianfernandez01** [comment]
Sorry for delay in replying. I was doing some tests because I appeared again the error mentioned at the beginning of the issue:
```   
 The service "gos_web_socket.router.wamp" has a dependency on a non-existent service   "gos_pubsub_router.websocket".
```
My mistake was that they did not include the bundle pubsub to AppKernel.php. Now that the server did worked properly, i.e. the error disappeared.
But now my problem is that when I define a route in my AppBundle / Resources / config / pubsub / routes.yml file as follows:
```
    app_topic_chat:
        channel: app/chat/{user_id}
        handler:
            callback: 'app.topic' 
        requirements:
            user_id:
                pattern: "\d+"
```
And when I use this code in the client's view (chat.html.twig):
```
var websocket = WS.connect("ws://127.0.0.1:8080");
myWebSocket.on("socket/connect", function(session){
         session.subscribe("app/chat/32", function(uri, payload){
        console.log("Received message", payload.msg);
    });
    console.log("Successfully Connected!");
})

myWebSocket.on("socket/disconnect", function(error){
    console.log("Disconnected for " + error.reason + " with code " + error.code);
})
```
I have the following error:
```
         ERROR: Unable to find route for app/chat/32
```
I don`t understand how to define correctly the routes for this.
I have also defined a Topic class with getName () appropriate (return 'app.topic '; ) and i configure this Topic as a service. I have also configured the bundle WebSocketBundle this:
```
gos_web_socket:
    server:
        host: 127.0.0.1
        port: 8080
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
```
Could you give me a clue as to clearly define these routes ?. Because of that I'm lost
Thanks for you patience

**Comment by ProPheT777** [comment]
> My mistake was that they did not include the bundle pubsub to AppKernel.php. Now that the server did worked properly, i.e. the error disappeared.

Nice catch, I forgot to update this docs section, I fixed it.

For the second, it can be a miss configuration.

You said that you have defined the routing definition in AppBundle / Resources / config / pubsub / routes.yml

and in your configuration you have 

```yaml
gos_web_socket:
    server:
        host: 127.0.0.1
        port: 8080
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
```

According to your routing file name it should be : 

```yaml
gos_web_socket:
    server:
        host: 127.0.0.1
        port: 8080
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routes.yml
```
