### ISSUE TITLE
Problems with push data!

### ISSUE THREAD

**Issue by arckdash** [GeniusesOfSymfony/WebSocketBundle#131]
Hi, I've a question, I'm having problems with de push notification with dinamyc routes! :S

**From a Controller** I'm doing this:
// Push Data
            $pusher = $this->container->get('gos_web_socket.zmq.pusher');
            $pusher->push([
                    'userId' => $user->getId(),
                    'userName' => $user->getLastName() . ', ' . $user->getFirstName(),
                    'avatar' => $user->getAvatar()
                ], 'class_students_connections', 
                array(
                    'idClass' => $session->getId()
                )
            );

In **pubsub/routing.yml**have this:
class_students_connections:
    channel: class/connections/channel/{idClass}
    handler:
        callback: 'autogestion.class.students.connection' 

**In my client**, the connection with the socket server is Successfully, and the channel with i trying to connect is:
var channel = "class/connections/channel/" + idClass;
console.log(channel);   //class/connections/channel/1

session.subscribe(channel, function(uri, data) {
console.log('data: ' + data );
console.log('userName: ' + data.userName );
});

**Class ConnectionTopic** The topic already implement TopicInterface, PushableTopicInterface,
and its function getName() is:
public function getName()
    {
        return 'autogestion.class.students.connection';
    }

and its function onPush() is:
public function onPush(Topic $topic, WampRequest $request, $data, $provider)
    {
        $topic->broadcast($data);
    }

I'm doing something wrong ??
Why can't get the push message in the client side ? :(

**Comment by matthieuy** [comment]
Do you declare your `ConnectionTopic` class like a service and with the tag `gos_web_socket.topic`?
Add `requirements` in your `pubsub/routing.yml` :
```yaml
class_students_connections:
    channel: class/connections/channel/{idClass}
    handler:
        callback: 'autogestion.class.students.connection'
    requirements:
        idClass: '\d+'
```

**Comment by arckdash** [comment]
I add 
requirements:
        idClass: '\d+'

But when I do push get this Exception:  :S
 request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Gos\Bundle\PubSubRouterBundle\Tokenizer\Token::setRequirements() must be of the type array, string given, called in /var/www/html/evaluados/vendor/gos/pubsub-router-bundle/Tokenizer/Tokenizer.php on line 52 and defined" at /var/www/html/evaluados/vendor/gos/pubsub-router-bundle/Tokenizer/Token.php line 79 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Gos\\Bundle\\PubSubRouterBundle\\Tokenizer\\Token::setRequirements() must be of the type array, string given, called in /var/www/html/evaluados/vendor/gos/pubsub-router-bundle/Tokenizer/Tokenizer.php on line 52 and defined at /var/www/html/evaluados/vendor/gos/pubsub-router-bundle/Tokenizer/Token.php:79)"} []

**Comment by matthieuy** [comment]
Excuse me, use that :
```yaml
class_students_connections:
    channel: class/connections/channel/{idClass}
    handler:
        callback: 'autogestion.class.students.connection'
    requirements:
        idClass:
            pattern: '\d+'
```
what about your `ConnectionTopic` ? How do you declare it in your `services.yml` ?
