### ISSUE TITLE
Problem with configure SSL websocket connection

### ISSUE THREAD

**Issue by arckdash** [GeniusesOfSymfony/WebSocketBundle#135]
Hi, I've a problem with ssl websocket connection, I already read this:
- https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Ssl.md
- https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/64
- https://github.com/ratchetphp/Ratchet/issues/161

But, I can't understand how figure it out! :S

I had a http web socket connection and it worked fine, but now, I've to work with https, i already have configured the ssl certificates in my domain, but i can't do work the wss connection.

my configuration is:
**config.yml**
```
gos_web_socket:
    pushers:
        zmq:
            default: true
            host: ip_server
            port: 55555
            persistent: true
            protocol: tcp
    server:
        port: 62108        
        host: ip_server   
        router:
            resources:
                - '@AutogestionBundle/Resources/config/pubsub/routing.yml'
```
I installed stunnel, with this configuration:
**/etc/stunnel/myconfig.conf**
```
cert = /etc/ssl/project_folder/certificate.crt
key = /etc/ssl/project_folder/certificate.key

chroot = /var/run/stunnel4/
pid = /var/run/stunnel4/websocket.pid   // I think this is wrong, but I don't know what to put here.
#userId
setuid = nobody

#group id
#groupid = nobody

[websockets]
accept = 8443
connect = 62108
```
**The web page dose this**:
```
var websocket = WS.connect("wss://ip_server:8443");
```
In the console i can see this:
```
WebSocket connection to 'wss://ip_server:8443/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
Can someone tell what I doing wrong ? :(
(I'm using apache server)

**Comment by arckdash** [comment]
Nobody?
@ProPheT777 
@matthieuy

**Comment by ProPheT777** [comment]
From my side nope sorry, your configuration looks good to me

**Comment by matthieuy** [comment]
I had a same  problem  and  I changed the  configuration, I post it when I can (problaly this weekend)
-- 
Send from my  phone
Matthieu

**Comment by ProPheT777** [comment]
Have you some log or something in order to figure out? That can be very
helpful :)

**Comment by arckdash** [comment]
I can't find out the log file! :( 

Do you know where is it?

**Comment by ProPheT777** [comment]
for nginx depends of your conf, check inside /var/log/nginx_err.log (or something like that, for the name of log file)

**Comment by matthieuy** [comment]
I use something like that in config for log file :
```yaml
monolog:
    handlers:
        websocket:
            type: stream
            path:  "%kernel.logs_dir%/%kernel.environment%_socket.log"
            level: debug
            channels: ['websocket']
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event, !websocket]
```

Do you use an IP or the hostname/domain in your configuration file ?
