### ISSUE TITLE
Authenticated users as anon

### ISSUE THREAD

**Issue by BraveFart** [GeniusesOfSymfony/WebSocketBundle#136]
Hello everyone ! 
I'm currently trying to use the WebSocketBundle in my project but I'm having some issues !

I've already done this in another project and everything worked just fine ! But I wanted to use the SonataAdminBundle so I created a new project and tried the same thing !! But when an authenticated user subscribe to a channel I get the following in the console :
`[2016-04-09 14:39:04] websocket.DEBUG: INSERT CLIENT 1530 {"user":"s:36:\"anon-8812448825708f7e877ef8041502078\";"}
[2016-04-09 14:39:04] websocket.INFO: anon-8812448825708f7e877ef8041502078 connected {"connection_id":1530,"session_id":"8812448825708f7e877ef8041502078","storage_id":1530}
`
instead of `username connected......`

Everything is working fine and the session are stored in the database, the web server and the websocket server are working in the same ip : (localhost) I tried deleting all the cookies from my web browser and trying again but nothing worked !!

this is my websocket config :

```yaml
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: localhost   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: admin
        session_handler: @session.handler.pdo
    pushers:
        zmq:
            default: true
            host: 127.0.0.1
            port: 5555
            persistent: true
            protocol: tcp
```

**Comment by ProPheT777** [comment]
Are you sure to be authenticated through admin firewall?

**Comment by BraveFart** [comment]
Yes !! I have two firewalls !! And I'm sure the user is authenticated thru this one !
I even tried the other firewall but no luck

```yaml
    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true

        # -> end custom configuration

        # default login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

```

**Comment by hermandinho** [comment]
having the same issue here. any solution available? thanks

**Comment by matthieuy** [comment]
Did you change the session name or use the default name (PHPSESSID) ?

**Comment by BraveFart** [comment]
No !! I'm just using the default one !

![image 2](https://cloud.githubusercontent.com/assets/11446602/14460885/df926e66-00b7-11e6-8191-d6b591401580.png)

**Comment by BraveFart** [comment]
I also tried the following code just to make sure that the user is under the `admin `firewall !

```php 
$securityContext = $this->get('security.context');
$token = $securityContext->getToken();
$providerKey = $token->getProviderKey(); // admin

dump($providerKey);
```
I get the following result !

![image 3](https://cloud.githubusercontent.com/assets/11446602/14462350/8b858c20-00be-11e6-83e8-034a3522ca22.png)

**Comment by leahpar** [comment]
Hello,
I'm having the same issue. Symfony profiler shows user is authenticated, but console keeps showing anonymous users (`websocket.INFO: anon-16709564465714e5063f16f267455790 connected`).
![capture d ecran 2016-04-18 a 15 53 13](https://cloud.githubusercontent.com/assets/3596831/14606544/0d5cb84a-057e-11e6-9cc4-5973a3c41c1c.png)

I'm using memcached session handler which implements \SessionHandlerInterface :
```yaml
framework:
    session:
        handler_id:  session.handler.memcached

gos_web_socket:
    client:
        firewall: main
        session_handler: session.handler.memcached
```

**Comment by BraveFart** [comment]
Okay, By dumping some variables I found out that the `$authenticationProvider` inside the `ClientManipulator` looks like this :


> #authenticationProvider: Gos\Bundle\WebSocketBundle\Client\Auth\WebsocketAuthenticationProvider {#89
>     #tokenStorage: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage {#88
>         -token: Symfony\Component\Security\Core\Authentication\Token\AnonymousToken {#979 ÔÇª5}
>     }
>     #firewalls: array:2 [
>         0 => "admin"
>         1 => "main"
>     ]
>     #logger: Symfony\Bridge\Monolog\Logger {#92}
>     #clientStorage: Gos\Bundle\WebSocketBundle\Client\ClientStorage {#93}
> }

Not sure if that means Something !!

**Comment by BraveFart** [comment]
@ProPheT777 @matthieuy Any suggestions guys ! I'm stuck with this for a week now !! And I tried everything !!

**Comment by ProPheT777** [comment]
Can you reproduce the bug on a fork of https://github.com/GeniusesOfSymfony/WebsocketAppDemo ? This is too much complex to debug you without a playground. 

I'm so sorry that we can't help you much.

**Comment by leahpar** [comment]
Of course it just work perfectly on a fork of WebsocketAppDemo !
I restarted my project on the WebsocketAppDemo base and now it works, but i can't find what is the difference...

**Comment by ProPheT777** [comment]
Can I close it

**Comment by BraveFart** [comment]
I still can't fin a solution yet ! But anyway I'll start all over and try again ! And yes you can close it if you want to !
Thanks for the help

**Comment by techsot** [comment]
i'm having the same issue ! any solution ?

**Comment by Eragon666** [comment]
We are having the same problem aswell.

**Comment by edusalguero** [comment]
Hi, I have the same problem and I found how to fix it and it is simple:

> The firewall name must be the firewall context name if exist. Else the firewall name. 

I follow the [setup guide](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md) and here
```yml
gos_web_socket:
    client:
        firewall: secured_area
```
**secured_area** must be the firewall context name if exist. Else the firewall name. 

If you have a security configuration like this https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/136#issuecomment-207827663

You must set the context instead of the firewall name:
```yml
gos_web_socket:
    client:
        firewall: user
```
Here is the problem: https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/44e7cac0009c4f4cd7c56e758d24f8b7bb5d453e/Client/Auth/WebsocketAuthenticationProvider.php#L71

Also if you use SNC Redis I think that you should set `snc-redis.session.locking` false
