### ISSUE TITLE
notification from controller

### ISSUE THREAD

**Issue by wajaja** [GeniusesOfSymfony/WebSocketBundle#141]
Hi;
I want to send a notification from the controller;
e.g: after publishing a message on the blog; open websocket  connection and send the notification on the route  "blog / channel".
please show me how can i do this.

**Comment by ProPheT777** [comment]
Have you checkout this : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md ?

**Comment by wajaja** [comment]
yes; 
I've in my controller; 
here is my configuration :

services.yml 
```
services:
    site_media.topic_media_service:
        class: Site\MediaBundle\Topic\MediaTopic
        tags:
            - { name: gos_web_socket.topic }
```

SiteMediaBundle/Resources/config/pubsub/routing.yml:
```media_topic:
    channel: media/channel
    handler:
        callback: 'media.topic' 
```
in  controller:
`$pusher = $this->container->get('gos_web_socket.zmq.pusher');
                //push(data, route_name, route_arguments)
  $store = $pusher->push(['my_data' => 'data '], 'media_topic');`  

when i do var_dump(store) i'll get null. but in console notification working
