### ISSUE TITLE
onPush() function not getting hit after push from controller using ZMQ

### ISSUE THREAD

**Issue by sujit13666** [GeniusesOfSymfony/WebSocketBundle#159]
**Config.yml**

```
gos_web_socket:
    topics:
      - @app.real_time.subscribe
      - @app.real_time.push
    server:
        port: 8000        #The port the socket server will listen on
        host: localhost   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main #can be an array of firewalls
        session_handler: @session.handler.pdo
    pushers:
        zmq:
            default: true
            host: 127.0.0.1
            port: 8888
            persistent: true
            protocol: tcp
```

**pubsub/routing.yml**

```
real_time_push:
    channel: all/user
    handler:
        callback: 'app.real_time.push' #related to the getName() of your topic
```

**services.yml**

```
app.real_time.subscribe:
        class: AppBundle\RealTime\Subscribe
        arguments: [ @gos_web_socket.websocket.client_manipulator ]
app.real_time.push:
        class: AppBundle\RealTime\Push
        arguments: [ @gos_web_socket.websocket.client_manipulator ]
```

The following function is getting hit when client subscribes on this topic. I can see the text in the console.

**Subscribe Class onSubscribe() : Subscribe.php**

```
public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        var_dump("This user is subscribed");
    }
```

But when pushed via **zmq** from controller the `onPush()` function never got hit. I have already implemented `TopicInterdace` and `PushableTopicInterface` in Push.php.

**Push Class onPush() : Push.php**

```
public function onPush(Topic $topic, WampRequest $request, $data, $provider)
    {
        var_dump("Helloooooooooooooooooo0000000000");   
    }
```

Please can any one tell me where did I do wrong. Thanks in advance. Here is the controller

```
$pusher = $this->container->get('gos_web_socket.zmq.pusher');
//push(data, route_name, route_arguments)
$pusher->push(['my_data' => 'data'], 'real_time_push', ['username' => 'sujit']);
```

**Comment by sujit13666** [comment]
@ProPheT777 Please have a look. I am stuck for 2 days now.

**Comment by ProPheT777** [comment]
Why do you segregate these services?

```yml
      - @app.real_time.subscribe
      - @app.real_time.push
```

subscribe and push are part of the same class, I think the problem is here.

**Comment by sujit13666** [comment]
@ProPheT777 Sorry for late response. I just modified to this configuration but same problem.Subscribing is fine but ```onPush()``` is not working.

**config.yml**
```
gos_web_socket:
    topics:
      - @app.real_time.subscribe_and_push
      #  - @app.real_time.push
    server:
        port: 8000        #The port the socket server will listen on
        host: localhost   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main #can be an array of firewalls
        session_handler: @session.handler.pdo
    pushers:
        zmq:
            default: true
            host: 127.0.0.1
            port: 8888
            persistent: true
            protocol: tcp
```
**pubsub/routing.yml**
```
real_time_subscribe_push:
    channel: all/user
    handler:
        callback: 'app.real_time.subscribe_and_push' #related to the getName() of your topic
```
**services.yml**
```
app.real_time.subscribe_and_push:
        class: AppBundle\RealTime\SubscribeAndPush
        arguments: [ @gos_web_socket.websocket.client_manipulator ]
```
**SubscribeAndPush Class onSubscribe() : SubscribeAndPush.php**
```
public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        var_dump("Subscribed..............."); //This is working like a charm
        // TODO: Implement onSubscribe() method.
    }
```
![subscribed](https://cloud.githubusercontent.com/assets/5456641/15954724/2cdbf60c-2efc-11e6-85e0-c49eddf73bfd.png)

**SubscribeAndPush Class onPush() : SubscribeAndPush.php**
```
public function onPush(Topic $topic, WampRequest $request, $data, $provider)
    {
        var_dump("PUSHED................."); //Never got hit
        // TODO: Implement onPush() method.
    }
```

**Controller**
```
$pusher = $this->container->get('gos_web_socket.zmq.pusher');
//push(data, route_name, route_arguments)

$pusher->push(['my_data' => 'data'], 'real_time_subscribe_push', ['username' => 'sujit']);
```
