### ISSUE TITLE
PubSub Routing use. 

### ISSUE THREAD

**Issue by KrissMcCone** [GeniusesOfSymfony/WebSocketBundle#17]
Hello, after update with pubsub, I change my code to send user id with subscribe not with every message.

My routing
```yaml
acme_topic:
    channel: chat/{room}/{token}/{user}
    handler:
        callback: 'chat.topic'
    requirements:    
        room:
            pattern: "\d+"
        token:
            pattern: "[A-Za-z0-9]+"
        user:
            pattern: "\d+"
            wildcard: true
```
The user has wildcard, because for one room every has another. 

The problem is that users subsribe to:
chat/30/8ad77e0b4d5c1f5d8b6d/2
and
chat/30/8ad77e0b4d5c1f5d8b6d/0

are not in the same room. They don't see the same messages.

Maybe I did sth wrong.

Thanks in advance. :)
