### ISSUE TITLE
Problem with share session.

### ISSUE THREAD

**Issue by KrissMcCone** [GeniusesOfSymfony/WebSocketBundle#20]
Hello I try to share sesssion by this tutorial: https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md 

My configuration:

```yml
# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 0.0.0.0   #The host ip to bind to
        router:
            resources:
                - @AppChatBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: secured_area
        session_handler: @session.handler.pdo
        storage:
            driver: @gos_web_socket.client_storage.driver.predis
            decorator: @gos_web_socket.client_storage.doctrine.decorator
            
# Doctrine cache        
doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 127.0.0.1
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis         
# SNC           
snc_redis:
    clients:
        ws_client:
            type: predis
            alias: client_storage.driver #snc_redis.client_storage.driver
            dsn: redis://127.0.0.1/2
            logging: %kernel.debug%
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
```

ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58: The service "gos_web_scocket.client_storage.driver.predis" has a dependency on a non-existent service "snc_redis.cache".

I've installed SNC and Redis Bundle.

**Comment by ProPheT777** [comment]
Docs was wrong, apply this change and let me know if that work.

https://github.com/GeniusesOfSymfony/WebSocketBundle/commit/c397212952a7d30fcb8c6b289dd5ff2a0a817b61

**Comment by KrissMcCone** [comment]
# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 0.0.0.0   #The host ip to bind to
        router:
            resources:
                - @AppChatBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: secured_area
        session_handler: @session.handler.pdo
        storage:
            driver: @gos_web_socket.client_storage.driver.predis
            
# Doctrine cache        
doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 127.0.0.1
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis         
# SNC           
snc_redis:
    clients:
        cache:
            type: predis
            alias: cache #snc_redis.cache
            dsn: redis://127.0.0.1/2
            logging: %kernel.debug%
            options:
                connection_timeout: 0
                read_write_timeout: 30


Thank you! Now, there is my config, but still the error:

The service "gos_web_socket.client_storage" has a dependency on a non-existent service "gos_web_socket.client_storage.driver.predis".

**Comment by ProPheT777** [comment]
This time the docs is right :D

Checkout https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md#create-your-own-driver

> NOTE : Predis driver class is included in GosWebSocketBundle, just register the service like below to use it.

```yml
services:
    gos_web_scocket.client_storage.driver.predis:
        class: Gos\Bundle\WebSocketBundle\Client\Driver\PredisDriver
        arguments:
            - @snc_redis.cache
```

**Comment by KrissMcCone** [comment]
Yes, I have bad service name linked. Thanks. :)

Fatal error: Call to a member function beginTransaction() on a non-object in /Applications/XAMPP/xamppfiles/htdocs/2match/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php on line 445


                                                                       
  [Symfony\Component\Debug\Exception\FatalErrorException]              
  Error: Call to a member function beginTransaction() on a non-object  
                                                                       

Now I have error in symfony engine, lolz. Do you know sth about it?

**Comment by ProPheT777** [comment]
Yes, your PDO session handler is not correctly setup.

http://symfony.com/doc/master/cookbook/configuration/pdo_session_storage.html

**Comment by KrissMcCone** [comment]
I've configured this by this tutorial

session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - { db_username: %database_user%, db_password: %database_password% }


And probably everyting works, cos I can login and my session is saved in database.

**Comment by ProPheT777** [comment]
I will dig into it so

**Comment by KrissMcCone** [comment]
Thanks so : )

**Comment by ProPheT777** [comment]
Symfony PdoSessionHandler bug when dsn (instead of inject pdo instance directly) is used in loop event context. 

I have write this part docs : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md

**Comment by KrissMcCone** [comment]
Thank you. :)


                                            
  [Predis\Connection\ConnectionException]   
  Operation timed out [tcp://0.0.0.0:6379] 

Now this after connected some user. Hard to do...

**Comment by ProPheT777** [comment]
Redis is installed ? (BTW redis driver is optional and proposed to illustrate a concret exemple, you can leave by default to fallback on php driver)

**Comment by KrissMcCone** [comment]
Yes, some play with configs helps me. :) Thank you


https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md

-> Retrieve current user

You have double use Ratchet\ConnectionInterface; in the topic class. :)

**Comment by ProPheT777** [comment]
Nice catch ! Just fixed thank you !

May the docs on Session setup part is confused and orient people to use another driver to store client ?

**Comment by KrissMcCone** [comment]
I would add there informaton that you have to install redis server. Rest there is ok, i think. Good job! :)
http://redis.io/

**Comment by KrissMcCone** [comment]
Probably works, but can't use it in topic. hahaha :P

use Gos\Bundle\WebSocketBundle\Client\WebSocketUserTrait;
use Gos\Bundle\WebSocketBundle\Topic\TopicInterface;
use Gos\Bundle\WebSocketBundle\Client\ClientStorageInterface;
use Gos\Bundle\WebSocketBundle\Router\WampRequest;
use Ratchet\ConnectionInterface;
use Ratchet\Wamp\Topic;
use App\ChatBundle\Entity\ChatMessage;
use Doctrine\ORM\Mapping as ORM;

**
     * Constructor
     *
     * @param \Doctrine\ORM\EntityManager $em
     * @param ClientStorageInterface $clientStorage
     */
    public function __construct(\Doctrine\ORM\EntityManager $em, ClientStorageInterface $clientStorage)
    {
        $this->em = $em;
        $this->clientStorage = $clientStorage;
    }

Error:

[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Catchable Fatal Error: Argument 2 passed to App\ChatBundle\Topic\ChatTopic  
  ::__construct() must be an instance of Gos\Bundle\WebSocketBundle\Client\Cl  
  ientStorageInterface, none given, called in /Applications/XAMPP/xamppfiles/  
  htdocs/app/app/cache/dev/appDevDebugProjectContainer.php on line 2366 an  
  d defined   



I've tried to use full path in argument but didn't help.

**Comment by ProPheT777** [comment]
It's normal, you must inject $clientStorage service `@gos_web_socket.client_storage` into your Topic via the depency injection (like you inject your entity manager)

**Comment by KrissMcCone** [comment]
I'm really sorry but it still doesn't work. 

Now,  Fatal Error: Fatal Error: Call to undefined method App\ChatBundle\Topic\ChatTopic::getCurrentUser()

I have:

use Gos\Bundle\WebSocketBundle\Client\WebSocketUserTrait;

So the topic clas doesn't add method from trait, but why lol.

**Comment by ProPheT777** [comment]
```php
class AcmeTopic implements TopicInterface
{
    use WebSocketUserTrait;
```

**Comment by KrissMcCone** [comment]
Ohhh, kill me better!!! :(

Now it works, but session isn't shared. I have to test it.

**Comment by ProPheT777** [comment]
> I also removed DoctrineCacheBundle and SncRedis. Default is the best. :D 

Sure. Use it when you'll have 1000 concurrent users :dancer: 

If the session is not shared it's due to your domain.

The domain between your websocket must be the same as your website. Because we use the cookie to auth the user.

Some working example : 

Webserver | Websocket
127.0.0.1:80 | 127.0.0.1:8080 -> WORK
127.0.0.1:80 | localhost:8080 -> NOT WORK
my-app.dev:80 | my-app.dev:8080 -> WORK
my-app.dev:80 | 127.0.0.1:8080 -> NOT WORK

I hope that will help you.

**Comment by KrissMcCone** [comment]
[2015-05-25 16:52:04] websocket.INFO: Launching Ratchet on localhost:8080  
http://localhost/app/web/app_dev.php/chat/open/82

$this->getCurrentUser($connection) return anon-5563377bbd5b7; 

Should work 😡😡😡

**Comment by ProPheT777** [comment]
Your user is authenticated from symfony2 application ?

**Comment by KrissMcCone** [comment]
yes.

**Comment by ProPheT777** [comment]
Have you check the firewall name used in websocket bundle is the same than your security.yml ?

**Comment by KrissMcCone** [comment]
firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer: false
                success_handler: login_success_handler 
                
            logout:       true
            anonymous:    true

**Comment by ProPheT777** [comment]
Just take your example above, adapt since you update.

```yaml
# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 0.0.0.0   #The host ip to bind to
        router:
            resources:
                - @AppChatBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main #HERE IS THE CHANGE
        session_handler: @session.handler.pdo
        storage:
            driver: @gos_web_socket.client_storage.driver.predis
```

**Comment by KrissMcCone** [comment]
Works perfectly. Thanks a lot. I hope that this topic helps another newbie in symfony like me.

**Comment by ProPheT777** [comment]
I will continue to improve the docs to be more explicit because the installation of this bundle is heavy and wrap a lot features bring by symfony.

**Comment by ewertoncode** [comment]
Hi!
I yet has this problem: 
PHP Fatal error:  Call to a member function beginTransaction() on null in /var/www/APSEAB/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php on line 445
[2015-06-27 12:51:26] php.EMERGENCY: Fatal Error: Call to a member function beginTransaction() on null {"type":1,"file":"/var/www/APSEAB/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php","line":445,"level":-1,"stack":[]} 


                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]      
  Error: Call to a member function beginTransaction() on null  
                                                               


I'm not use redis, my configs:

# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @TonChatBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main #can be an array of firewalls
        session_handler: @session.handler.pdo

_________________

services:
    ton_chat.topic_chat_service:
        class: Ton\ChatBundle\Topic\ChatTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: ["@gos_web_socket.client_storage"]

    pdo:
        class: PDO
        arguments:
            dsn: mysql:host=%database_host%;dbname=%database_name%
            user: %database_user%
            password: %database_password%
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, {lock_mode: 0}]


My server is runing in: 127.0.0.1:8000, and websoket in: 127.0.0.1:8080.

Can help me?

Tanks!

**Comment by ProPheT777** [comment]
Yes, 

```yml
services:
session.handler.pdo:
class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
public: false
arguments:
- "mysql:host=%database_host%;dbname=%database_name%"
- { db_table: sessions, db_username: %database_user%, db_password: %database_password% }
```

This definition is wrong.

First of all you need to turn PDO as service like following:

```yml
pdo:
    class: PDO
    arguments:
        dsn: mysql:host=%database_host%;dbname=%database_name%
        user: %database_user%
        password: %database_password%
    calls:
        - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
```

Because `Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler` require it.

and then declare the session handler service:

```yml
session.handler.pdo:
    class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments: [@pdo, {lock_mode: 0}]
```

and then it should work
