### ISSUE TITLE
Redis server went away

### ISSUE THREAD

**Issue by dawivan** [GeniusesOfSymfony/WebSocketBundle#206]
Hi, I'm having trouble connecting to the redis database, in my config.yml file:

```
doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 192.168.3.75
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis
```
I can connect to redis from the Redis Desktop Manager application without any problems.
Any ideas? Thank you
