### ISSUE TITLE
Establishing connection in Prod env failed

### ISSUE THREAD

**Issue by AienTech** [GeniusesOfSymfony/WebSocketBundle#207]
Hey guys,
tnx for this awesome bundle, it works perfectly for our project
the only problem is it won't work on production environment even though I'm running `app/console gos:websocket:server --env=prod`

in developer console it shows `WebSocket connection to 'ws://0.0.0.0:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

is there any workarounds or solution for that?

**Comment by ProPheT777** [comment]
Hey,

There are logs from client side right? Can you provide log from server side
please.

Make sure to clear cache of env prod, accept connection from the firewall.

Without log from your application I can't help you. Connection refused mean
something is up and running but rejected. Have you à proxy un front of your
websocket, like nginx? If yes you can Also dig into it.

**Comment by AienTech** [comment]
Unfortunately logs are empty, I even used `console.log()` and saw `app/logs/prod.log` but they both are empty. Also I'm using apache as my webserver and I'm pretty sure there aren't anything running in this port. my firewall also allows 8080 from anywhere (I'm just using `ufw`).

Also just for double checking I changed the port from 8080 to 66554 and nothing.

Is there any other info that I can provide for you?

**Comment by AienTech** [comment]
maybe this can help:

```
"symfony/symfony": "^2.8",
"gos/web-socket-bundle": "^1.8",
```

and the `config.yml`:
```
gos_web_socket:
    pushers:
        wamp:
            host: %websocket_host% #(0.0.0.0)
            port: %websocket_port% #(8080)
    shared_config: true
    server:
        port: %websocket_port%        #(0.0.0.0)
        host: %websocket_host%   #8080
        router:
            resources:
                - @AdministrationSystemBundle/Resources/pubsub/router.yml
```
