### ISSUE TITLE
Disconnected for Connection lost

### ISSUE THREAD

**Issue by jokari4242** [GeniusesOfSymfony/WebSocketBundle#211]
Hi!

Thanks for this nice bundle,

I have a pb, like a timeout or i don't know...

When the page is loaded, everything works well, user are authentified, and can suscribe to room.

When a little period of inactivity or when i'm using back navigator function, i have this message, in console of developper tools:
```
Disconnected for Connection lost - scheduled 1th reconnect to occur in 5 second(s). with code 6
```

And when i'm publish something :
```
Uncaught Autobahn not connected
```

Here, the script use for connect client to websocket
```
    {#WEBSOCKET ONLY IF CONNECTED#}
    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        {{ ws_client() }}

        <script>
            var _WS_URI = "ws://{{ uri }}:{{ gos_web_socket_server_port }}";
            var websocket = WS.connect(_WS_URI);

            websocket.on("socket/connect", function(session){
                var event = CustomEvent('web-socket:ready', { 'detail': { session: session } } );

                window.dispatchEvent(event);
            });

            websocket.on("socket/disconnect", function(error){
                console.log("Disconnected for " + error.reason + " with code " + error.code);

            });

            (function () {
                function CustomEvent ( event, params ) {
                    params = params || { bubbles: false, cancelable: false, detail: undefined };
                    var evt = document.createEvent( 'CustomEvent' );
                    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
                    return evt;
                }

                CustomEvent.prototype = window.Event.prototype;

                window.CustomEvent = CustomEvent;
            })();


        </script>

        {{  render(controller('jokari4242ChatBundle:Chat:getChat'))  }}
    {% endif %}
```

If someone can help me, thanks a lot :-)

**Comment by murman-lexus** [comment]
I have the same problem.

**Comment by MicioBaus** [comment]
Anyone was able to solve this issue?

**Comment by trandangtri** [comment]
I got the same problem and have no idea to fix this one.

**Comment by murman-lexus** [comment]
Hello. what messages you have in log of your WebsocketServer?

**Comment by sobha-sudheesh** [comment]
Hi, anyone got a fix to this issue?

**Comment by haskasu** [comment]
I am having the same issue. does anyone knows what it is?

**Comment by murman-lexus** [comment]
@haskasu try looking here: https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/299

**Comment by murman-lexus** [comment]
@haskasu try this https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/197

**Comment by MicioBaus** [comment]
I think the ping should be from the client.
The server should close any inactive connection after a timeout, to avoid running out of resources.

    var pingpong = function (){
        session.publish( myroute , {message: "ping"});
    };

    var intervalvar = setInterval(pingpong, timeout_in_milliseconds);

**Comment by Evgen14** [comment]
Hi, anyone was able to solve this issue?

**Comment by murman-lexus** [comment]
> Hi, anyone was able to solve this issue?

 try this #197 (comment)

**Comment by Gradius30** [comment]
This seems to be also happening to me since Evgen14 reported it. Any solution so far?

**Comment by klodoma** [comment]
Related to #351. Does anyone has this running on Symfony 4?

**Comment by mbabker** [comment]
The [demo app](https://github.com/GeniusesOfSymfony/WebsocketAppDemo) was upgraded to run Symfony 4.2 over the weekend and personally I've got an app in production I upgraded to Symfony 4.2 last Friday (upgraded from 3.4 to 4.1 4 months ago).  So whatever issue you're running into is not related to Symfony version support.

**Comment by murtho** [comment]
I'm also running this bundle (v1.8.13) in a Symfony 4.1.7 application without problems

**Comment by mbabker** [comment]
There's also a 1.x branch on the demo app corresponding with the 1.x branch on this repo.

**Comment by klodoma** [comment]
> There's also a 1.x branch on the demo app corresponding with the 1.x branch on this repo.

Didn't noticed that. I'll have a look. Thanks!

**Comment by klodoma** [comment]
Ok, I've solved it for my case. I had these missing in services.yml:

```

    # RPC handlers need to have the `gos_web_socket.rpc` tag, so by convention we will tag all handlers in the directory
    AppBundle\Rpc\:
        resource: '../../src/AppBundle/Rpc'
        tags:
            - { name: gos_web_socket.rpc }

    # RPC handlers need to have the `gos_web_socket.topic` tag, so by convention we will tag all handlers in the directory
    AppBundle\Topic\:
        resource: '../../src/AppBundle/Topic'
        tags:
            - { name: gos_web_socket.topic }


```
