### ISSUE TITLE
Problem with session

### ISSUE THREAD

**Issue by AntoineTesson** [GeniusesOfSymfony/WebSocketBundle#240]
Hi, with symfony 3.3 we cant use this method : 

```
pdo:
    class: PDO
    arguments:
        dsn: mysql:host=%database_host%;dbname=%database_name%
        user: %database_user%
        password: %database_password%
    calls:
        - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

session.handler.pdo:
    class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments: [@pdo, {lock_mode: 0}]

```
Because they refused 2 arguments , and dsn node is not recognized...
but the new way for this cause lot of 
`PHP Fatal error:  Call to a member function beginTransaction() on a non-object in /var/www/vhosts/sd-106489.dedibox.fr/kergafa.com/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php on line 439`

how set lock mode on the new way ?

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }

**Comment by AntoineTesson** [comment]
ok for this lock_mode just

        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }
            - {lock_mode: 0}

But   how fix   

  calls:
        - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

**Comment by AntoineTesson** [comment]
strange but ok:

        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }
            - {lock_mode: 0}
            - [ setAttribute, [3, 2] ]

i waiting if this new config twhrow exceptions as : 
[HP Fatal error: Call to a member function beginTransaction() on a non-object in /var/www/vhosts/sd-106489.dedibox.fr/kergafa.com/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php on line 439](url)

**Comment by AntoineTesson** [comment]
We dont need set calls:
- [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
because
`    private function connect($dsn)
    {
        $this->pdo = new \PDO($dsn, $this->username, $this->password, $this->connectionOptions);
        $this->pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
        $this->driver = $this->pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);
    }`

But with new way.... i have sometimes on the production 
PHP Fatal error: Call to a member function beginTransaction() on a non-object in /var/www/vhosts/sd-106489.dedibox.fr/kergafa.com/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php on line 439

So where is the problem on Symfony 3.3 ?

**Comment by murman-lexus** [comment]
Hi everybody.  My configuration on **sf3.3**:

pdo:
    class: PDO
    arguments:
        - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
        - '%database_user%'
        - '%database_password%'
    calls:
        - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

session.handler.pdo:
    class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments: [@pdo, {lock_mode: 0}]

**Comment by vittore** [comment]
@murman-lexus can you post complete config.yml? I'm missing something.

Thanks in advance.

**Comment by murman-lexus** [comment]
@vittore 
```
framework:
    session:
        handler_id: session.handler.pdo
services:
    pdo:
        class: PDO
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - '%database_user%'
            - '%database_password%'
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ['@pdo', {lock_mode: 0}]

gos_web_socket:
    server:
        port: "%websocket_port%"     #The port the socket server will listen on
        host: "%websocket_server%"   #The host ip to bind to
        router:
            resources:
                - '@ChatBundle/Resources/config/pubsub/routing.yml'
    client:
        firewall: main
        session_handler: session.handler.pdo
```
