### ISSUE TITLE
Error establishing connection in SSL

### ISSUE THREAD

**Issue by igorjacon** [GeniusesOfSymfony/WebSocketBundle#272]
Hi,
I'm trying to configure websocket in SSL, I've followed the instructions [here](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Ssl.md) but I'm still getting the following error:

> WebSocket connection to 'wss://enuovo.fail:8443/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

Here is my stunnel configuration:
<img width="798" alt="screen shot 2017-12-03 at 19 05 20" src="https://user-images.githubusercontent.com/16034579/33528222-54c54e8c-d85d-11e7-8f0f-ea793173d813.png">

my websocket config:
```yml
gos_web_socket:
    server:
        port: %web_socket_server.port%
        host: %domain%.%ltd%
        router:
            resources:
                - "@EnuovoWebSocketBundle/Resources/config/routing.yml"
    client:
        firewall: ["super_admin", "admin", "shop"]
        session_handler: "@session.handler.pdo"
    pushers:
        wamp:
            host: %domain%.%ltd%
            port: %web_socket_server.port%
```
I then run my websocket server like so:
`php bin/console gos:websocket:server -a enuovo.fail -e=prod -n`

```
18:49:16 INFO      [websocket] Starting web socket [] []
18:49:16 INFO      [websocket] Register periodic callback Gos\Bundle\WebSocketBundle\Periodic\PdoPeriodicPing, executed each 20 seconds [] []
18:49:16 INFO      [websocket] Launching Ratchet on enuovo.fail:8080 PID: 7181 [] []
```
So my websocket server is running on port 8080, which is the connect port specified in my stunnel config, and in my JS I connect to the websocket with the accept port:
```javascript
var _WS_URI = "wss://{{ gos_web_socket_server_host }}:8443";
var messageWebSocket = WS.connect(_WS_URI);
```

Can someone tell me what I am doing wrong?
Here is my stunnel log:
<img width="825" alt="screen shot 2017-12-03 at 19 25 04" src="https://user-images.githubusercontent.com/16034579/33528387-d0ac2c9e-d85f-11e7-89e9-9323b16b4e81.png">

Everything seems to be running fine but I still get this connection error. :/
