### ISSUE TITLE
WebSocket connection to 'ws://0.0.0.0:8070/' failed: Error in connection establishment

### ISSUE THREAD

**Issue by alandwiprasetyo** [GeniusesOfSymfony/WebSocketBundle#273]
Hi, i have some problem when deploy on production, I have error in my console

`WebSocket connection to 'ws://0.0.0.0:8070/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Thank for helping me

**Comment by fariz0020** [comment]
Hello ALL !

We get same issue here, our project work well on local, but after deployed on production, the socket get error.

here some code we made change 

base.html.twig
```
var _WS_URI = "ws://{{ gos_web_socket_server_host }}:{{ gos_web_socket_server_port }}"; 
var webSocket = WS.connect(_WS_URI);
webSocket.on("socket/connect", function(session){
```
config.yml
```
gos_web_socket:
    shared_config: true
    server:
        port: '%gos_web_socket_port%'        #The port the socket server will listen on
        host: '%gos_web_socket_host%'   #The host ip to bind to
        router:
            resources:
                - "@CoreBundle/Resources/config/routing_notification.yml"
    pushers:
        wamp:
            host: '%gos_web_socket_host%'   #The host icp to bind to
            port: '%pusher_socket_port%'        #The port the socket server will listen on
```

parameters.yml
```
parameters:
...
gos_web_socket_host: 0.0.0.0
gos_web_socket_port: 8070
pusher_socket_port: 1337
```

default-ssl.conf
```
<VirtualHost *:80>
...
     SSLEngine on
     SSLCertificateFile /var/www/html/docker/ssl/server.crt
     SSLCertificateKeyFile /var/www/html/docker/ssl/server.key
     SSLCertificateChainFile /var/www/html/docker/ssl/server.crt
...
</VirtualHost>
```

we has follow some issues threads but still get error
#251 
#97 

here is the command we use for deployment
`app/console gos:websocket:server --env=prod`

the last step we did were configure the SSL in default-ssl.conf

Thank you very much for you help !

@ProPheT777 @CoalaJoe @mbabker
