### ISSUE TITLE
Connect a user to the server using FOSUser

### ISSUE THREAD

**Issue by navalex** [GeniusesOfSymfony/WebSocketBundle#305]
Hi,

I'm trying to create a chat with Gos WebSocketBundle, and i try to found a solution to only allow users connected to the website (using FOSUserBundle) to publish msg in my chat topic but i have no idea to how to do that.
Is there an issue to my problem ?

Thanks, Navalex.

**Comment by i-telligence-af** [comment]
How are you setting up the ws connection on the client side?

Can you post your security.yml?

**Comment by ma-gu-16** [comment]
exaclty same config and same prob here. 

session after frontend user login succesfull saved in database. 

but websocket debug:

`
12:26:21 INFO      [websocket] Starting web socket
12:26:21 INFO      [websocket] Launching Ratchet on 127.0.0.1:8942 PID: 1234
12:26:21 DEBUG     [websocket] INSERT CLIENT 2468 ["user" => "s:36:"anon-5395846205c52db5da4b81427641409";"]
12:26:21 INFO      [websocket] anon-5395846205c52db5da4b81427641409 connected ["connection_id" => 2468,"session_id" => "5395846205c52db5da4b81427641409","storage_id" => 2468]`

i thougth it should be the user object.
if i debug onSubscribe function:
`
        $user = $this->clientManipulator->getClient($connection);
        var_dump($user);`

Result: 
string(36) "anon-5395846205c52db5da4b81427641409"

whats wrong?

**Comment by ma-gu-16** [comment]
its still an issue. maybe someone has an solution ?

**Comment by mbabker** [comment]
The config looks fine.

For the session bit to work correctly, it needs to be able to parse the session cookie from the main website.  If your websocket subdomain is different from your website subdomain (i.e. for one of my clients we have `ws.example.com` for the websocket connections and `www.example.com` for the main site), then the session cookie needs to be configured to allow all subdomains:

```yaml
framework:
    session:
        cookie_domain: '.example.com'
```

**Comment by ma-gu-16** [comment]
> The config looks fine.
> 
> For the session bit to work correctly, it needs to be able to parse the session cookie from the main website. If your websocket subdomain is different from your website subdomain (i.e. for one of my clients we have `ws.example.com` for the websocket connections and `www.example.com` for the main site), then the session cookie needs to be configured to allow all subdomains:
> 
> ```yaml
> framework:
>     session:
>         cookie_domain: '.example.com'
> ```

yes this is set. 

webapp runs at: https:/portal.domain.local and websocket runs at: ws://127.0.0.1:1337

**Comment by ma-gu-16** [comment]
services
```
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
      - { db_table: 'symfony_user_session', db_id_col: 'guid' }
```

framework
```

  session:
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    gc_maxlifetime: 36000
    cookie_secure: false
    cookie_samesite: null
    cookie_domain: '.local'
    name: SFSESSID
```
gos

```
gos_web_socket:
  client:
    session_handler: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    firewall: main
```
