### ISSUE TITLE
Symfony 4 php 7.1 Disconnected for Connection was closed properly [WS-1007: ] with code 0

### ISSUE THREAD

**Issue by mohamedyasser** [GeniusesOfSymfony/WebSocketBundle#316]
after i make example like https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md

console log show
Disconnected for Connection was closed properly [WS-1007: ] with code 0

config/packages/gos_web_socket.yaml

```
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.1.7   #The host ip to bind to
        router:
              resources:
                  - '%kernel.project_dir%/config/pubsub/routing.yml'
```

config/pubsub/routing.yml

```
acme_topic:
    channel: acme/channel
    handler:
        callback: 'acme.topic'
acme_rpc:
    channel: news/{method}
    handler:
        callback: 'news.rpc'
```

News Topic service class

```
class NewsTopic implements TopicInterface
{
    /**
     * This will receive any Subscription requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     * @return void
     */
    public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this will broadcast the message to ALL subscribers of this topic.
        $topic->broadcast(['msg' => 'hello' . " has joined "]);
    }

    /**
     * This will receive any UnSubscription requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     * @return void
     */
    public function onUnSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this will broadcast the message to ALL subscribers of this topic.
        $topic->broadcast(['msg' => 'hello' . " has left " . $topic->getId()]);
    }


    /**
     * This will receive any Publish requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     * @param $event
     * @param array $exclude
     * @param array $eligible
     * @return mixed|void
     */
    public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
        /*
        	$topic->getId() will contain the FULL requested uri, so you can proceed based on that

            if ($topic->getId() === 'acme/channel/shout')
     	       //shout something to all subs.
        */

        $topic->broadcast([
            'msg' => $event,
        ]);
    }

    /**
     * Like RPC is will use to prefix the channel
     * @return string
     */
    public function getName()
    {
        return 'acme.topic';
    }
}
```
