### ISSUE TITLE
Custom cookie name on firewall

### ISSUE THREAD

**Issue by proArtex** [GeniusesOfSymfony/WebSocketBundle#332]
This issue reopens #89 because here is solution: pass 3d $options parameter (e.g. ['name' => 'CUSTOMNAME']) to SessionProvider's constructor. Take a look at protected function setOptions(array $options)

**Comment by proArtex** [comment]
Here is example:
```
# services.yml
 gos_web_socket.ws.server:
        class: Gos\Bundle\WebSocketBundle\Server\Type\WebSocketServer
        public: false
        lazy: true
        arguments:
            - ...
            - '@session.storage'
```
```
# WebSocketServer.php
...
new SessionProvider(
    $wsServer,
    $this->sessionHandler,
    ['name' => $this->sessionStorage->getName()]
),
...
```
