### ISSUE TITLE
Launch websocket server on production with SSL

### ISSUE THREAD

**Issue by dylanalizon** [GeniusesOfSymfony/WebSocketBundle#338]
Hey,

I can't launch the WS server.

My config: 

```
gos_web_socket:
    server:
        port: 8888        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - '%kernel.project_dir%/config/pubsub.yaml'
    client:
        firewall: main
        session_handler: '@session.handler.pdo'
```

stunnel.conf:

```
cert = /etc/letsencrypt/live/mysubdomain.mydomain.fr/fullchain.pem
key = /etc/letsencrypt/live/mysubdomain.mydomain.fr/privkey.pem

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

chroot = /var/run/stunnel4/
pid = /stunnel.pid

local = mysubdomain.mydomain.fr

[websockets]
accept = 8443
connect = mysubdomain.mydomain.fr:8888
```

But when i use this commande:

`bin/console gos:websocket:server -a mysubdomain.mydomain.fr -eprod`

i have this error:

`[console] Error thrown while running command "gos:websocket:server -a 'mysubdomain.mydomain.fr' -eprod". Message: "Given URI "tcp://mysubdomain.mydomain.fr:8888" does not contain a valid host IP" ["exception" => InvalidArgumentException { …},"command" => "gos:websocket:server -a 'mysubdomain.mydomain.fr' -eprod","message" => "Given URI "tcp://mysubdomain.mydomain.fr:8888" does not contain a valid host IP"] `

Someone have an idea ?

Ty
