### ISSUE TITLE
Disconnected for Connection lost - scheduled 1th reconnect to occur in 5 second(s). with code 6

### ISSUE THREAD

**Issue by klodoma** [GeniusesOfSymfony/WebSocketBundle#351]
Hi Guys, 

I am looking around since a while for a solution on this. 
The client gets constantly disconnected after connect. There are several reports on this, but I couldn't find a solution for it. 

I am using the examples provided here: https://github.com/GeniusesOfSymfony/WebsocketAppDemo

I was trying to setup WebSocketBundle on Symfony 4.1 and it works ONLY if I use the the "dev-master" 
version of the "gos/web-socket-bundle". With 1.8.3, 1.9* (all rc versions) it fails to work.

I am constantly getting the console message in the browser
`Disconnected for Connection lost - scheduled 1th reconnect to occur in 5 second(s). with code 6`

The console of the  gos:websocket:server looks like this:
![screenshot_229](https://user-images.githubusercontent.com/944350/49284200-22253100-f494-11e8-9d71-d1bd2f68b79b.png)

If I switch to the "dev-master" version of the "gos/web-socket-bundle", then everything works well. 

Is this a known issue? Any solution to get 1.8.3 working with Symfony 4.1?

I can provide more details if required. Thanks in advance!

**Comment by konshensx16** [comment]
Well the console is not repporting any errors, just one thing i noticed is that th user is annonm if you ever happen to set up an authentication system make sure to run you symfony app using 127.0.0.1 otherwise it wont workm because it wont recognize the "localhost" name, just throwing this out there because it caused some problems for me when i was starting out with GOS.

**Comment by klodoma** [comment]
> Well the console is not repporting any errors, just one thing i noticed is that th user is annonm if you ever happen to set up an authentication system make sure to run you symfony app using 127.0.0.1 otherwise it wont workm because it wont recognize the "localhost" name, just throwing this out there because it caused some problems for me when i was starting out with GOS.

Thanks for the info! Is your setup running with Symfony 4?

**Comment by konshensx16** [comment]
Yes i have it with symfony 4, the project is actually in my public repos if you want to check it out it's called "Fabour", it's nothing fancy but has most of the functionalities of GOS in place and working.

**Comment by klodoma** [comment]
> Yes i have it with symfony 4, the project is actually in my public repos if you want to check it out it's called "Fabour", it's nothing fancy but has most of the functionalities of GOS in place and working.

Thanks for the info. I'll have a look!

**Comment by mbabker** [comment]
The "user firewall is not configured" messages mean you need to set up the firewall in the bundle config.

```yaml
gos_web_socket:
    client:
        firewall: [ main ] # This is the line you must configure to silence the firewall message
        session_handler: '%app_session_handler%'
        storage:
            driver: '@cache.websocket' # This is using symfony/cache and defined under the framework.cache.pools node
            decorator: '@gos_web_socket.client_storage.symfony.decorator'
            ttl: 0
```

**Comment by ProPheT777** [comment]
May be should we not set a default firewall, and raise an error in console to be more explicit ? 

At the beginning I took that approach for beginner and having something working without a lot configuration.

**Comment by klodoma** [comment]
Those settings, do not fix the problem. I will create a repository with the problem, not sure why it's happening. Feedback will follow.

**Comment by klodoma** [comment]
I have found the issue. I've had these missing in services.yaml. 

```
    # RPC handlers need to have the `gos_web_socket.rpc` tag, so by convention we will tag all handlers in the directory
    AppBundle\Rpc\:
        resource: '../../src/AppBundle/Rpc'
        tags:
            - { name: gos_web_socket.rpc }

    # RPC handlers need to have the `gos_web_socket.topic` tag, so by convention we will tag all handlers in the directory
    AppBundle\Topic\:
        resource: '../../src/AppBundle/Topic'
        tags:
            - { name: gos_web_socket.topic }
```
