### ISSUE TITLE
How to get authenticated user

### ISSUE THREAD

**Issue by klodoma** [GeniusesOfSymfony/WebSocketBundle#355]
Can you help me to get the user? 

I followed the following documentation and some other examples, but I can't see to get the authenticated user. 
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md

`$user = $this->clientManipulator->getClient($connection);`
returns always "anon-13369767275c10d461a9ac2535372930"

Shared session is setup, the sockets seems to work. I assume it's a configuration issue. 

![screenshot_235](https://user-images.githubusercontent.com/944350/49860545-4ff66800-fdfa-11e8-9d14-4f8d7f8f1f62.png)

```
<?php

namespace AppBundle\Topic;

use Ratchet\ConnectionInterface;
use Gos\Bundle\WebSocketBundle\Client\ClientManipulatorInterface;
use Gos\Bundle\WebSocketBundle\Router\WampRequest;
use Gos\Bundle\WebSocketBundle\Topic\TopicInterface;
use Ratchet\Wamp\Topic;

class NotificationTopic implements TopicInterface
{
    /**
     * @var ClientManipulatorInterface
     */
    protected $clientManipulator;

    /**
     * @param ClientManipulatorInterface $clientManipulator
     */
    public function __construct(ClientManipulatorInterface $clientManipulator)
    {
        $this->clientManipulator = $clientManipulator;
    }

    /**
     * @param ConnectionInterface $connection
     * @param Topic $topic
     */
    public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        $user = $this->clientManipulator->getClient($connection);
        dump($user);
        $topic->broadcast(['msg' => $connection->resourceId . " has  joined " . $topic->getId()]);
    }

    /**
     * This will receive any UnSubscription requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     */
    public function onUnSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this will broadcast the message to ALL subscribers of this topic.
        $topic->broadcast(['msg' => $connection->resourceId . " has left " . $topic->getId()]);
    }

    /**
     * This will receive any Publish requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     * @param $event
     * @param array $exclude
     * @param array $eligible
     */
    public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
        /*
            $topic->getId() will contain the FULL requested uri, so you can proceed based on that

            if ($topic->getId() == "acme/channel/shout")
               //shout something to all subs.
        */

        $topic->broadcast([
            'msg' => $event
        ]);
    }

    /**
     * Like RPC is will use to prefix the channel
     * @return string
     */
    public function getName()
    {
        return 'notifications.topic';
    }
}
```

services.yaml:
```
    acme.notification:
        class: MappsBundle\Topic\NotificationTopic
        arguments: ['@gos_web_socket.websocket.client_manipulator']
        tags:
            - { name: gos_web_socket.topic }
```

gos_web_socket.yaml
```
# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - '@AppBundle/Resources/config/pubsub/routing.yml'
    pushers:
        wamp:
            host: 127.0.0.1
            port: 8080

    client:
        #firewall: secured_area #can be an array of firewalls
        firewall: [ main ] # This is the line you must configure to silence the firewall message
        session_handler: "@session.handler.pdo"
        storage:
            driver: '@cache.websocket' # This is using symfony/cache and defined under the framework.cache.pools node
            decorator: '@gos_web_socket.client_storage.symfony.decorator'
            ttl: 0
```

Any ideas?
