### ISSUE TITLE
contains unsupported keys for channel and handler

### ISSUE THREAD

**Issue by thehatami** [GeniusesOfSymfony/WebSocketBundle#371]
in symfony 4.2 i give this fatal error.
how can i solve it?

```
contains unsupported keys for "app_rpc": "channel", "handler". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition", "controller", "name_prefix", "trailing_slash_on_root"
```

here is my route
```
app_rpc:
  channel: app/notifier
  handler:
    callback: 'app.rpc'
  requirements:
    method:
      pattern: "[a-z_]+"

app_topic:
  channel: app/notifier
  handler:
    callback: 'app.topic'
```
