### ISSUE TITLE
"gos_web_socket.amqp.pusher" not found

### ISSUE THREAD

**Issue by thehatami** [GeniusesOfSymfony/WebSocketBundle#372]
how can i face to 'Service "gos_web_socket.amqp.pusher" not found?

**Comment by stipic** [comment]
`['my_data' => 'data']` = Payload
`user_notification` = name of your PubSub route
`['username' => 'user1'] `= params for your PubSub route (if needed)

example:

Let's say i have app_topic_chat PubSub route in my yaml file:

```
app_topic_chat:
    channel: 'conversation/{conversationId}'
    handler:
        callback: 'conversation.topic'
    requirements:
        conversationId:
            pattern: '\d+'

```
My push action in that topic will be something like this:

`$this->_pusher->push($payload, 'app_topic_chat', ['conversationId' => 1]);`
