### ISSUE TITLE
[SOLVED] (Another) How send push to specific user

### ISSUE THREAD

**Issue by thehatami** [GeniusesOfSymfony/WebSocketBundle#376]
according to document, i get user with name and default broadcast work for notify user with {ID} left. until here all things work good.

but when i try call push from controller, get error.

my controller has bind $pusher with ```@gos_web_socket.amqp.pusher```
```
$pusher->push(['my_data' => 'data'], 'chat_topic',
            array(
                'username' => $username
            )
        );
```
my pubsub router
```
chat_topic:
  channel: chat/uio/{username}
  handler:
    callback: 'chat.topic_service'
  requirements:
    username:
      pattern: '[a-zA-Z]+'
```

and my service
```
chat.topic_service:
    class: App\Topic\ChatTopic
    arguments: ["@gos_web_socket.websocket.client_manipulator"]
    tags:
      - { name: gos_web_socket.topic }
```

but i got these error:
```
Library error: connection closed unexpectedly - Potential login failure.
```
