### ISSUE TITLE
Websocket slow after a while

### ISSUE THREAD

**Issue by sercul** [GeniusesOfSymfony/WebSocketBundle#399]
Hello, on our system after some hours with not many users online (50-100) websocket start to connect very slow. So time after user opens the page till time when socket is connected can be even up to 20-120 seconds. We don't know really where to look, because our production server is rather powerful with 128gb of RAM. Could you suggest something please? 
We are using 
```
php 7.2
symfony 4.4
"gos/web-socket-bundle": "v2.0.0-rc",
"predis/predis": "^1.1",
"snc/redis-bundle": "dev-master",

```
Config:
```
gos_web_socket:
    pushers:
        wamp:
            enabled: true
            port: '%env(CHAT_SERVER_PORT)%'        #The port the socket server will listen on
            host: '%env(CHAT_SERVER_HOST)%'   #The host ip to bind to
            ssl: false
            origin: null
    server:
        port: '%env(CHAT_SERVER_PORT)%'        #The port the socket server will listen on
        host: '%env(CHAT_SERVER_HOST)%'   #The host ip to bind to
        router:
           resources:
               - '%kernel.project_dir%/config/pubsub.yml'

    client:
        firewall:
            - user
            - api 
        session_handler: '@snc_redis.session.handler'
        storage:
            driver: 'cache.app' # The service which should be decorated
            decorator: 'gos_web_socket.client.driver.symfony_cache'
```
