### ISSUE TITLE
Router mismatch for different topics

### ISSUE THREAD

**Issue by timmonster** [GeniusesOfSymfony/WebSocketBundle#40]
Hello,
 i dont know if ist a real bug but in my cas ist realy annoying.

I try to to implement three diferent topics with differnet routes

router.yml
```
eventri_event_push_sub:
    channel: notification/events/{event}
    handler:
        callback: 'eventri.subscribe.event.topic'


eventri_role_push_sub:
    channel: notification/roles/{role}
    handler:
        callback: 'eventri.subscribe.role.topic'


eventri_user_push_sub:
    channel: notification/users/{user}
    handler:
        callback: 'eventri.subscribe.user.topic'
```

but each time i try to connect to one route e.g. "eventri_role_push_sub" the first route "eventri_event_push_sub" matches.

This behavior also appears if i add the requirments to the parameter in the channel.

Thank you very much and greetings.
