### ISSUE TITLE
Error to install composer

### ISSUE THREAD

**Issue by Tywors** [GeniusesOfSymfony/WebSocketBundle#418]
I have this error when execute composer:
 
You have requested a non-existent parameter "gos_web_socket.server.host"

problem?
thanks!

**Comment by mbabker** [comment]
What version of the bundle?

It's been a long while since I've done a fresh install into a Symfony application, but IIRC the bundle's default configuration causes that error on a totally new install until you set things up.  And, last time I tried creating a recipe for the bundle I just ran into too many quirks with the recipe checker to make it work efficiently, so I haven't tried again to be able to avoid the initial error message.

Try this as a baseline for the bundle config, place it at `config/packages/gos_web_socket.yaml`:

```yaml
parameters:
    # Adds fallback params in case the corresponding env vars are not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(GOS_WEB_SOCKET_SERVER_IP): '127.0.0.1'
    env(GOS_WEB_SOCKET_SERVER_PORT): 1337

gos_web_socket:
    server:
        port: '%env(int:GOS_WEB_SOCKET_SERVER_PORT)%' # The port the socket server will listen on
        host: '%env(GOS_WEB_SOCKET_SERVER_IP)%'       # The host ip to bind to
        router:
            resources:
                -
                    resource: '%kernel.project_dir%/config/pubsub/websocket/*'
                    type: 'glob'
```
