### ISSUE TITLE
Unable to find route for acme/channel

### ISSUE THREAD

**Issue by NOaMTL** [GeniusesOfSymfony/WebSocketBundle#424]
Hello,

I tried to follow the Readme and I installed WebSocketBundle on a 5.2.6 Symfony.
I get this message "Unable to find route for acme/channel" when I subscribe to the topic from client
![image](https://user-images.githubusercontent.com/4923485/113981252-badbd080-9847-11eb-9cca-728921d43770.png)

this is my code : 
services.yaml
```
app.websocket.topic.acme:
        class: App\Websocket\Topic\AcmeTopic
        tags:
            - { name: gos_web_socket.topic }
```
![image](https://user-images.githubusercontent.com/4923485/113980814-35f0b700-9847-11eb-9ac3-0573dc3ed526.png)
My AcmeTopic is the exact same as in the Readme.

my gos_websocket.yaml
```
gos_web_socket:
  server:
    port: 8080        # The port the socket server will listen on
    host: 127.0.0.1   # The host ip to bind to
    router:
      resources:
        - '%kernel.project_dir%/config/pubsub/routing.yaml'
  client:
    firewall: main # Can be an array of firewalls
    session_handler: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
```
![image](https://user-images.githubusercontent.com/4923485/113980995-6df7fa00-9847-11eb-8d7b-aae1fbdf5ece.png)
my config/pubsub/routing.yaml
```
acme_topic:
  channel: acme/channel
  handler: 'acme.topic'
```

Also user is still anonymous while I see the session being stored in the sql.

Thank you.
