### ISSUE TITLE
Cannot dump definition because of invalid class name ('database_connection:getWrappedConnection')

### ISSUE THREAD

**Issue by krajcikondra** [GeniusesOfSymfony/WebSocketBundle#431]
Hi,

I am using symfony 5 with gos/web-socket-bundle 3.7.2.

```
session.handler.pdo:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments:
        - !service { class: PDO, factory: 'database_connection:getWrappedConnection' }
        - { lock_mode: 0 }
```

When I pass arguments in my services.yaml I get following error:

```
In PhpDumper.php line 1895:
                                                                                                      
 Cannot dump definition because of invalid class name ('database_connection:getWrappedConnection').
```

It`s bug or I have something wrong?

**Comment by mbabker** [comment]
I apparently need to update the docs but the inline service is using the old factory definition which is deprecated, this should work:

```yaml
session.handler.pdo:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments:
        - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
        - { lock_mode: 0 }
```

Alternatively, you can pass your database DSN which will create a separate connection to the database instead of reusing the connection from the Doctrine connection service:

```yaml
session.handler.pdo:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments:
        - '%env(resolve:DATABASE_URL)%'
        - { lock_mode: 0 }
```
