### ISSUE TITLE
Unable to find route for channel

### ISSUE THREAD

**Issue by claudissimus** [GeniusesOfSymfony/WebSocketBundle#439]
Hello,

basically I have the same problem as discussed here : https://github.com/GeniusesOfSymfony/WebSocketBundle/discussions/425

I've followed the docs to configure the bundle and now I am stuck at the point where it does not seem to load my pubsub configuration.

This is my bundle config:
```
gos_web_socket:
  server:
    port: 8050        #The port the socket server will listen on 8888 in prod / 8888 not working on dev machine
    host: 127.0.0.1   #The host ip to bind to
    keepalive_ping: true
    keepalive_interval: 45
    router:
      resources:
        # Prototype
        -
            resource: '%kernel.project_dir%/config/pubsub_websocket/*'
            type: 'glob'

```
No files are loaded out of the resource folder. Using yaml as type and referencing the file directly also does not work.  (I can enter any garbage into that yml without error  - file not loaded)

My pubsub:
```
global_topic:
    # A unique URI pattern to identify this topic handler 
    pattern: global/channel

    # Must match the `getName` method of your Topic class
    callback: 'global.topic'

```

Console output:
```
00:13:14 DEBUG     [websocket] GET CLIENT 2502
00:13:14 INFO      [websocket] User anon-96035768461314c7a7f179929276386 subscribed to global/channel
00:13:14 ERROR     [websocket] Unable to find route for global/channel
00:13:14 ERROR     [websocket] Unable to find route for global/channel
```

I am not sure if this is a bug of the bundle or of the documentation, however I kindly ask for advice.
I used to work with v2 of this bundle with Symfony 3.4 without a problem.

Problem occurs with Symfony 5.3.7

Thanks.
