### ISSUE TITLE
integrate sessions with fosuserbundle

### ISSUE THREAD

**Issue by informatico-madrid** [GeniusesOfSymfony/WebSocketBundle#44]
Hi. I will try get a fos user entity in my topic. I did put security context in argument, but this context is not related with fos?
```
//My topic definition

...
class JoaoImTopic implements TopicInterface
{
    private $context;

    public function __construct(SecurityContext $securityContext){
        $this->context= $securityContext;
    }
...
}
```

```
//My service definition and config:
services:
    pdo:
    class: PDO
    arguments:
      dsn: mysql:host=127.0.0.1;port=null;dbname=informatico-madrid
      user: %database_user%
      password: %database_password%
    calls:
      - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

  session.handler.pdo:
    class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    public:    false
    arguments:
        - "mysql:dbname=informatico-madrid"
        - %pdo.db_options% 
parameters:
    pdo.db_options:
        db_table:    sessions
        db_id_col:   sess_id
        db_data_col: sess_data
        db_time_col: sess_time
        db_lifetime_col: sess_lifetime
        db_username: %database_user% 
        db_password: %database_password%
framework:
   ...
    session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  ~
        handler_id: session.handler.pdo
   ...
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @JoaoImWebBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main #can be an array of firewalls
        session_handler: @session.handler.pdo
    topics:
        - @joaoim_webbundle.topic_sample_service
doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 127.0.0.1
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis
```
