### ISSUE TITLE
Authenticating Users with native file sessions

### ISSUE THREAD

**Issue by gdw96** [GeniusesOfSymfony/WebSocketBundle#443]
Hi,

I'm stuck on a problem that I haven't found a solution yet, I've tried too many things to tell. Here is the reason for this issue.

I would like to set up a websocket channel allowing users to receive their notifications on the site. But for that I need to check if the user is authenticated and I need to know who he is to send his notifications to him only.

Note: I am using localhost for development (Symfony CLI web server).

So, here is where I stand:

For the storage of sessions I use the native_file handler. I started by declaring it as a :

```yaml
# config/services.yaml
imports:
    - { resource: 'parameters.yaml' }

services:
    app.session.handler.native_file:
        public: true
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler
        arguments:
            - '%app.session.native_file.save_path%'
```

Then I configured the framework to use this service for session management and so far everything works fine:

```yaml
# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    session:
        handler_id:      'app.session.handler.native_file'
        cookie_secure:   'auto'
        cookie_samesite: 'lax'
```

For your information, here is my current security configuration:

```yaml
# config/packages/security.yaml
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    enable_authenticator_manager: true # Necessary to login throttling. See: https://symfony.com/doc/current/security/experimental_authenticators.html
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
    password_hashers:
        App\Entity\User\User:
            algorithm: auto # Auto-selects the best possible hashing algorithm.
    firewalls:
        main:
            anonymous: false # Must be false with `enable_authenticator_manager: true`.
            lazy:      true
            provider:  app_user_provider
            login_throttling: # See: https://symfony.com/doc/current/security.html#limiting-login-attempts and framework.rate_limiter in framework.yaml
                max_attempts: 3 # 3 login attempts per minute.
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: logout
                invalidate_session: false
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 1_296_000 # 15 days in seconds
                path: /
```

Now my current gos_websocket configuration:

```yaml
# config/packages/gos_web_socket.yaml
gos_web_socket:
    authentication:
        enable_authenticator: true
        providers:
            session:
                session_handler: 'app.session.handler.native_file'
                firewalls:       'main'
        storage:
            type: in_memory
    server:
        # The host IP address on the server which connections for the websocket server are accepted.
        host: 127.0.0.1
        # The port on the server which connections for the websocket server are accepted.
        port: 8080

        origin_check: true

        router:
            resources:
                -
                    resource: '%kernel.project_dir%/config/pubsub/websocket/*'
                    type: 'glob'
```

Finally, I created a Topic, the NotificationsTopic:

```php
<?php

namespace App\Websocket\Topic;

use App\Entity\User\User;
use Gos\Bundle\WebSocketBundle\Authentication\ConnectionRepositoryInterface;
use Gos\Bundle\WebSocketBundle\Router\WampRequest;
use Gos\Bundle\WebSocketBundle\Topic\TopicInterface;
use Ratchet\ConnectionInterface;
use Ratchet\Wamp\Topic;

class NotificationsTopic implements TopicInterface {
    private ConnectionRepositoryInterface $connectionRepository;

    public function __construct(ConnectionRepositoryInterface $connectionRepository) {
        $this->connectionRepository = $connectionRepository;
    }

    public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request) {
        $user = $this->connectionRepository->getUser($connection); // empty string
        $topic->broadcast(['msg' => gettype($user) . ' : ' . $user]);
        $user = $this->connectionRepository->findTokenForConnection($connection)->getUser(); // empty string
        $topic->broadcast(['msg' => gettype($user) . ' : ' . $user]);

        if (!$user instanceof User) {
            $topic->broadcast(['msg' => $connection->resourceId . ' has joined ' . $topic->getId()]);
        } else {
            $topic->broadcast(['msg' => $connection->resourceId . ' (' . $user->getEmail() . ') has joined ' . $topic->getId()]);
        }

        $topic->broadcast(['msg' => 'SessionId: ' . $connection->WAMP->sessionId]); // Generated session ID
        $topic->broadcast(['msg' => 'SessionId: ' . $connection->Session->getId()]); // null (or empty string ?)

        // TODO: Implement onSubscribe() method.
    }

    public function onUnSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request) {
        $topic->broadcast(['msg' => $connection->resourceId.' has left '.$topic->getId()]);
        // TODO: Implement onUnSubscribe() method.
    }

    /**
     * @inheritDoc
     */
    public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible) {
        $topic->broadcast(['msg' => $event]);
        // TODO: Implement onPublish() method.
    }

    /**
     * Name of the topic.
     * @return string
     */
    public function getName(): string {
        return 'notifications.topic';
    }
}
```

And finally his statement as a service:

```yaml
    # Websocket services
    App\Websocket\Topic\NotificationsTopic:
        tags:
            - { name: gos_web_socket.topic }
```

---

This is what I get:
No errors are returned (neither in the logs nor elsewhere), however all my attempts to get the user end up with an empty string.

`$connection->WAMP->sessionId` does return a session id but it doesn't match any available sessions.
And `$connection->Session->getId()` returns nothing.

I don't know what to try anymore, what to do for the moment.

Does anyone have any ideas?

Thanks in advance,
