### ISSUE TITLE
Connection could not be established

### ISSUE THREAD

**Issue by krajcikondra** [GeniusesOfSymfony/WebSocketBundle#449]
Hi, 

something went wrong me. My websocket worked recently fine but now I cant estabilish connection.

May related this error? I am not sure if it is User deprecated or exception.

```
[2021-10-19T22:14:57.151205+02:00] php.INFO: User Deprecated: Since gos/web-socket-bundle 3.1: The "gos_web_socket.event_listener.register_push_handlers" service is deprecated and will be removed in GosWebSocketBundle 4.0. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since gos/web-socket-bundle 3.1: The \"gos_web_socket.event_listener.register_push_handlers\" service is deprecated and will be removed in GosWebSocketBundle 4.0. at /var/www/html/var/cache/dev/ContainerXdoxQWR/getGosWebSocket_EventListener_RegisterPushHandlersService.php:22)"} []
```

Except above error in terminal output is no problem and log folder is empty.

Is my config deprecated?

```
gos_web_socket:
    server:
        port: 8888        # The port the socket server will listen on
        host: 127.0.0.1   # The host ip to bind to
        router:
            resources:
                - '%kernel.project_dir%/config/pubsub/routing.yaml'
    client:
        firewall: [api, login, dev, main] # Can be an array of firewalls
        session_handler: 'session.handler.pdo'
````
