### ISSUE TITLE
After upgrading Symfony from 5.3.0 to 5.3.13, gos:wsb gives error when client attempts to subscribe to channel

### ISSUE THREAD

**Issue by damoclark** [GeniusesOfSymfony/WebSocketBundle#461]
Hey Michael,

I was using WebSocketBundle authenticated sessions successfully with Symfony 5.3.0 by following your [legacy authentication system instructions](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/auth.md).  

My PdoSessionhandler config is as follows:

```yaml
    # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/SessionSetup.md#define-a-session-handler-service
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            # https://github.com/GeniusesOfSymfony/WebSocketBundle/discussions/433#discussion-3406371
            - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            - { lock_mode: 1 } # LOCK_ADVISORY
```

However, after I upgraded my Symfony version from 5.3.0 to 5.3.13, and am getting the following error message from rachet server when an authenticated web client attempts to connect:

```
In PdoSessionHandler.php line 441:
                                                                               
  Argument 1 passed to Symfony\Component\HttpFoundation\Session\Storage\Handl  
  er\PdoSessionHandler::connect() must be of the type string, object given, c  
  alled in /Users/clarkd/Documents/Development/php/work/oras/vendor/symfony/h  
  ttp-foundation/Session/Storage/Handler/PdoSessionHandler.php on line 271     
                                                                               

gos:websocket:server [-m|--profile] [-a|--host [HOST]] [-p|--port [PORT]] [--] [<name>]

{"level":"error","message":"command \"symfony console gos:websocket:server\" failed: exit status 255, waiting 5 seconds before restarting it"}
```
I have the following versions of gos:wsb

```
gos/pubsub-router-bundle             v2.7.1    Symfony PubSub Router Bundle
gos/web-socket-bundle                v3.13.0   Symfony Web Socket Bundle
gos/websocket-client                 v1.5.0    WAMP client in PHP
doctrine/dbal                        3.2.1     Powerful PHP database abstra...
```

I have configured gos:wsb as follows:

```yaml
# Reference for options
# https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/ConfigurationReference.md
gos_web_socket:
  server:
    host: '%env(GOS_WEB_SOCKET_SERVER_IP)%'       # The host ip to bind to
    port: '%env(int:GOS_WEB_SOCKET_SERVER_PORT)%' # The port the socket server will listen on
    origin_check: true
    router:
      resources:
        - '%kernel.project_dir%/config/pubsub/routing.yaml'

  origins: ['origin1','origin2']

  # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/SessionSetup.md#configure-the-session-handler
  client:
    firewall: main # Can be an array of firewalls
    session_handler: 'session.handler.pdo'

# ...
```

I started gos:wsb under xdebug and added a breakpoint at line 271 for `PdoSessionHandler` class. 

```php
    /**
     * @return bool
     */
    #[\ReturnTypeWillChange]
    public function open($savePath, $sessionName)
    {
        $this->sessionExpired = false;

        if (null === $this->pdo) {
            $this->connect($this->dsn ?: $savePath);  // <-- This is line 271
        }

        return parent::open($savePath, $sessionName);
    }
```
 
Argument 1 `$this->dsn` according to the debugger is an instance of `\Doctrine\DBAL\Driver\PDO\Connection`.  

In the constructor for `PdoSessionHandler`, because `$pdoOrDsn` is not an instance of `\PDO` and its not a string, it is being assigned directly to the `dsn` property.   

```php
    public function __construct($pdoOrDsn = null, array $options = [])
    {
        if ($pdoOrDsn instanceof \PDO) {
            if (\PDO::ERRMODE_EXCEPTION !== $pdoOrDsn->getAttribute(\PDO::ATTR_ERRMODE)) {
                throw new \InvalidArgumentException(sprintf('"%s" requires PDO error mode attribute be set to throw Exceptions (i.e. $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION)).', __CLASS__));
            }

            $this->pdo = $pdoOrDsn;
            $this->driver = $this->pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);
        } elseif (\is_string($pdoOrDsn) && str_contains($pdoOrDsn, '://')) {
            $this->dsn = $this->buildDsnFromUrl($pdoOrDsn);
        } else {
            $this->dsn = $pdoOrDsn; // <--- being assigned here
        }
```

I'm not sure why it is getting passed the wrong instance during dependency injection.  This error only occurs in the rachet server.  The web server for my Symfony app works fine with `PdoSessionHandler`.

Michael, have I done something stupid, or could this issue be related to the recent breaking changes in Doctrine\DBAL, with the update to v3?  The previous version of DBAL was 2.12.0 when gos:wsb was working.

Thanks for sharing the work you do with this bundle.

Cheers,
Damien.

**Comment by mbabker** [comment]
Update your session handler config based on https://symfony.com/doc/current/session/database.html#store-sessions-in-a-relational-database-mariadb-mysql-postgresql and you should be fine.

**Comment by damoclark** [comment]
Thanks Michael for responding so quickly.  

I had a look at my `config/services.yaml` file and I already have that set correctly according to the documentation.  

What's baffling me is that the authentication configuration is working fine with the built in symfony/php web server, serving pages in my app.  It's only the rachet server instance authenticating websocket client connections that yields this error.  

This is what I already had in full, pertaining to gos:wsb in `config/services.yaml` and was working before updating to 5.3.13.  I haven't changed anything here while problem-solving.

```yaml
    # The introduction of the Session Sharing and User Authentication with WebsocketBundle requires a
    # defined session handler service.  The documentation suggests using Pdo, and is a good choice
    # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/SessionSetup.md
    # https://symfony.com/doc/current/session/database.html#store-sessions-in-a-relational-database-mariadb-mysql-postgresql
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'

    # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/SessionSetup.md#define-a-session-handler-service
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            # https://github.com/GeniusesOfSymfony/WebSocketBundle/discussions/433#discussion-3406371
            - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            - { lock_mode: 1 } # LOCK_ADVISORY

    # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/Pusher.md#using-a-pusher
    # Wired the service so it can be used in PusherClient service by Messenger Workers and API endpoints
    # to send out push websocket messages
    Gos\Bundle\WebSocketBundle\Pusher\PusherInterface: '@gos_web_socket.pusher.wamp'

```

I've tried going through the call stack in my debugger to figure out where the wrong parameter is being set, but I'm afraid that my knowledge of Symfony internals is too lacking to figure it out.

What do you think?

Damien.

**Comment by mbabker** [comment]
Your `session.handler.pdo` service definition still uses the object based constructor.  Which, depending on the environment (Symfony env, installed and active bundles, etc.), can mean that the inline service reference doesn’t always kick back a PDO instance from the DBAL.  So make sure your database handler config always uses a string param to make sure it always works right.

**Comment by damoclark** [comment]
Yep, that nailed it!  

Thanks so much Michael for your help.  

Changing this:

```yaml
    # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/SessionSetup.md#define-a-session-handler-service
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            # https://github.com/GeniusesOfSymfony/WebSocketBundle/discussions/433#discussion-3406371
            - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            - { lock_mode: 1 } # LOCK_ADVISORY
```

to this, solved the issue:

```yaml
    # https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/SessionSetup.md#define-a-session-handler-service
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - '%env(DATABASE_URL)%'
            - { lock_mode: 1 } # LOCK_ADVISORY
```

Cheers,
D.
