### ISSUE TITLE
Call to a member function save() on a non-object in ClientStorage.php on line 97

### ISSUE THREAD

**Issue by maresc-g** [GeniusesOfSymfony/WebSocketBundle#75]
Hi,

I am trying to connect to the websocket server using the example code in the wiki. But I get the error
```
Call to a member function save() on a non-object in ClientStorage.php on line 97
```
Which must means that the driver is null even though I think I configured it.

Here is my services.yml
```yml
    pdo:
        class: PDO
        arguments:
            dsn: mysql:host=%database_host%;port=%database_port%;dbname=%database_name%
            user: %database_user%
            password: %database_password%
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, {lock_mode: 0}]

    gos_web_socket.client_storage:
        class: Gos\Bundle\WebSocketBundle\Client\ClientStorage
        arguments:
            - %web_socket_server.client_storage.ttl%
            - @?monolog.logger.websocket

    app.blinks_topic_service:
        class:  AppBundle\Topic\BlinksTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments:
          - @gos_web_socket.websocket.client_manipulator

    gos_web_scocket.client_storage.driver.predis:
        class: Gos\Bundle\WebSocketBundle\Client\Driver\PredisDriver
        arguments:
            - @snc_redis.cache
```
And here is the config.yml
```yml
doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 127.0.0.1
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis

snc_redis:
    clients:
        cache:
            type: predis
            alias: cache #snc_redis.client_storage.driver
            dsn: redis://127.0.0.1/2
            logging: %kernel.debug%
            options:
                connection_timeout: 0
                read_write_timeout: 30

gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main #can be an array of firewalls
        session_handler: @session.handler.pdo
        storage:
            driver: @gos_web_socket.client_storage.driver.predis
            decorator: @gos_web_socket.client_storage.doctrine.decorator
```

Thanks
