### ISSUE TITLE
Symfony PDO Session Handler when import project

### ISSUE THREAD

**Issue by JaimeJesusSerrano** [GeniusesOfSymfony/WebSocketBundle#87]
Hello, first of all, thank for the bundle and your work.

I saved my project in github, I formated my computer and imported the proyect. When I tried use the command:  ```sudo php app/console doctrine:database:create```

Appeared a error in the console: ```[PDOException] SQLSTATE[42000] [1049] Unknown database 'project_db'```
In the other hand if I try access to the web I get the same error:
```PDOException in ContainerBuilder.php line 892: SQLSTATE[42000] [1049] Unknown database 'project_db'```

```1. in ContainerBuilder.php line 892```
```2. at PDO->__construct('mysql:host=127.0.0.1; port=3306; dbname=project_db', 'root', 'pass')```
```3. at ReflectionClass->newInstanceArgs(array('dsn' => 'mysql:host=127.0.0.1; port=3306; dbname=project_db', 'user' => 'root', 'password' => 'pass')) in ContainerBuilder.php line 892```
```4. at ContainerBuilder->createService(object(Definition), 'pdo') in ContainerBuilder.php line 452```
```5. at ContainerBuilder->get('pdo', '1') in ContainerBuilder.php line 945```
```6. at ContainerBuilder->resolveServices(object(Reference)) in ContainerBuilder.php line 942```
```7. at ContainerBuilder->resolveServices(array(object(Reference), array('lock_mode' => '0'))) in ContainerBuilder.php line 869```
```8. at ContainerBuilder->createService(object(Definition), 'session.handler.pdo') in ContainerBuilder.php line 452```
```9. at ContainerBuilder->get(object(Alias)) in ContainerBuilder.php line 436```
```10. at ContainerBuilder->get('gos_web_socket.session_handler', '2') in PingableDriverCompilerPass.php line 18```
```11. at PingableDriverCompilerPass->process(object(ContainerBuilder)) in Compiler.php line 107```
```12. at Compiler->compile(object(ContainerBuilder)) in ContainerBuilder.php line 570```
```13. at ContainerBuilder->compile() in bootstrap.php.cache line 2633```
```14. at Kernel->initializeContainer() in bootstrap.php.cache line 2411```
```15. at Kernel->boot() in bootstrap.php.cache line 2442```
``` 16. at Kernel->handle(object(Request)) in app_dev.php line 28```

The problem is in my services.yml where I have:
```
services:
    pdo:
        class: PDO
        arguments:
            dsn: mysql:host=%database_host%;port=%database_port%;dbname=%database_name%
            user: %database_user%
            password: %database_password%
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        #public: false
        arguments: [@pdo, {lock_mode: 0}]
```
Because if I change it to, for example:
```
services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - { db_username: %database_user%, db_password: %database_password% }
```
The problem it's resolved.

My question is, why fail the first option? 

Also I don't understand why named dsn, user, password in the arguments, [ setAttribute, [3, 2] ] and lock_mode: 0, but it's normal because i'm a "initiated" with Symfony2.

Ty.
