### ISSUE TITLE
The parameter "gos_pubsub_registered_routers" must be defined.

### ISSUE THREAD

**Issue by acidmk** [GeniusesOfSymfony/WebSocketBundle#88]
Followed the tutorial and server is working fine but when i try to execute command 'php app/console cache:clear' it gives me this

![sockets1123](https://cloud.githubusercontent.com/assets/12675793/11561083/051d0676-99ef-11e5-8139-649f39b1ddb6.png)

and in config.yml i have this configuration
```
gos_web_socket:
    server:
        port: 8080             #The port the socket server will listen on
        host: 192.168.56.102   #The host ip to bind to
        router:
                resources:
                    - @ApplicationOrderBundle/Resources/config/pubsub/routing.yml
    topics:
        - @application_order.topic_sample_service
    pushers:
            wamp:
                host: 192.168.56.102
                port: 8080
```
