### ISSUE TITLE
Custom cookie name on firewall

### ISSUE THREAD

**Issue by lrauldan** [GeniusesOfSymfony/WebSocketBundle#89]
If you use a custom cookie name ( anything else other than PHPSESSID ) the socket server is unable to fetch user connecting to the socket.

I didn't get too far with debugging to find out where & why it happens but I was using a custom cookie name and when I switched to default one everything worked.

**Comment by lrauldan** [comment]
Might be directly related to Ratchet: https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Session/SessionProvider.php#L74

**Comment by ProPheT777** [comment]
In fact yes and no, because I use trick to replace the "official" ratchet by the gos fork https://github.com/GeniusesOfSymfony/Ratchet

So if you really need this feature a PR is welcome

**Comment by matthieuy** [comment]
I had the same problem ! I fixed it with this solution : 

set the session name in a variable in your `parameters.yml`
Adapt your `config.yml` to use it (in `framework.session.name`)
Create a event listener like this :
```
gos_start_listener:
        class: AppBundle\EventListener\ServerStartListener
        arguments:
            - %session_name%
        tags:
            - { name: kernel.event_listener, event: gos_web_socket.server_launched, method: 'onServerStart' }
```
Create the class `ServerStartListener`  :
```
class ServerStartListener
{
    private $session_name;

    public function __construct($session_name)
    {
        $this->session_name = $session_name;
    }

    public function onServerStart(ServerEvent $event)
    {
        ini_set('session.name', $this->session_name);
    }
}
```
