### ISSUE TITLE
You cannot create a service ("request") of an inactive scope ("request")

### ISSUE THREAD

**Issue by anboo** [GeniusesOfSymfony/WebSocketBundle#94]
`$ php app/console gos:websocket:server`
and this success worked!
```
[2015-12-27 20:11:14] websocket.INFO: Starting web socket  
[2015-12-27 20:11:14] websocket.INFO: Launching Ratchet on 127.0.0.1:8080 PID: 4167
```

After connect
```javascript
var socket = new WebSocket("ws://127.0.0.1:8080");
socket.onmessage = function(evt){ console.log("Socket Message received %o", evt); };
socket.send("hello");
```

console.log:
```
Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.(anonymous function) @ (index):74
(index):70 WebSocket connection to 'ws://127.0.0.1:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Console error:
```
  [Symfony\Component\DependencyInjection\Exception\InactiveScopeException]   
  You cannot create a service ("request") of an inactive scope ("request").  
                                                                             

gos:websocket:server [-m|--profile] [-a|--host [HOST]] [-p|--port [PORT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<name>]
```

Config.yml
```
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
    shared_config: false
```
