### ISSUE TITLE
WS set anon session for user not anonymous

### ISSUE THREAD

**Issue by anboo** [GeniusesOfSymfony/WebSocketBundle#96]
Configuration:
```
pdo:
        class: PDO
        arguments:
            dsn: mysql:host=%database_host%;port=%database_port%;dbname=%database_name%
            user: %database_user%
            password: %database_password%
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, {lock_mode: 0}]
```

config.yml:
```
framework:
   session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.pdo

......

gos_web_socket:
    server:
   ...
    client:
        firewall: secured_area #can be an array of firewalls
        session_handler: @session.handler.pdo
```

Topic code for print username to console
```php
public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
       $user = $this->clientManipulator->getClient($connection);
        $user1 = $this->container->get('security.token_storage')->getToken()->getUser();
        $connection->event($topic->getId(), ['msg' => 'lol, user with name - '.$user1.' - '.$user]);

        $topic->broadcast([
            'msg' => $event,
        ]);
    }
```

![Image of Yaktocat]
(http://cs627321.vk.me/v627321008/297b3/pS27cqbuM3Q.jpg)

But i not anonymous, why I have a anonymous session?

**Comment by ProPheT777** [comment]
Websocket and website are running on the same domain name ? I mean if you use a domain name for website and you register ws with IP (or different domain) it will not work because authentication is cookie based.

**Comment by anboo** [comment]
Oh, maybe I do not l know. How fix it?
I run web-server from symfony application.
Local domain of the application - network (local domain - 127.0.0.1)
Address for send sockets from client - 127.0.0.1:8080

**Comment by ProPheT777** [comment]
if you access to your website from netwoker.dev or something like that and you register websocket to network.dev:8080 it's ok.

In the security.yml, what is your firewall name ? secured_area ?

**Comment by anboo** [comment]
```
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/ask, role: ROLE_USER }
```

**Comment by ProPheT777** [comment]
ok so

```yaml
gos_web_socket:
    server:
   ...
    client:
        firewall: secured_area #can be an array of firewalls
        session_handler: @session.handler.pdo
```

should be :

```yaml
gos_web_socket:
    server:
   ...
    client:
        firewall: main #can be an array of firewalls
        session_handler: @session.handler.pdo
```

according to your security config
